### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by Borewit** [minht11/local-music-pwa#3]
`npm run build` results in:
```
> music-pwa@1.0.0 build C:\Users\Borewit\code\github\local-music-pwa
> rollup -c


src/main/app.ts, src/worklets/x-icon-worklet.ts → dist/...
rpt2: typescript version: 3.6.2
rpt2: tslib version: 1.9.3
rpt2: rollup version: 1.20.3
rpt2: rollup-plugin-typescript2 version: 0.20.1
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\app.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\worklets\x-icon-worklet.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\shared\x-icon-paths.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\app-shell.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\x-toast.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\info-view.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\x-menu.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\toasts\actions.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\menu\actions.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\library-view\library-view.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\player-panel\player-panel.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\shared-styles.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\index.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\utils\animation-curves.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\utils\utils.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\lib\supported.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\app\actions.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\player\actions.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\player\reducer.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\library\actions.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\grid-item.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\x-icon-button.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\x-dialog.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\x-select.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\store\library\reducer.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\track-list-item.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\library-view\library-view-styles.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\x-slider.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\player-panel\player-panel-styles.ts'
rpt2: transpiling 'C:\Users\Borewit\code\github\local-music-pwa\src\main\components\virtual-list.ts'
[!] (plugin rpt2) Error: src/main/components/virtual-list.ts:13:53 - error TS2306: File 'C:/Users/Borewit/code/github/local-music-pwa/node_modules/@types/resize-observer-bro
wser/index.d.ts' is not a module.

13 import { ResizeObserver, ResizeObserverEntry } from 'resize-observer-browser'
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~

src\main\components\virtual-list.ts
Error: src/main/components/virtual-list.ts:13:53 - error TS2306: File 'C:/Users/Borewit/code/github/local-music-pwa/node_modules/@types/resize-observer-browser/index.d.ts' i
s not a module.

13 import { ResizeObserver, ResizeObserverEntry } from 'resize-observer-browser'
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~

    at error (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup\dist\rollup.js:9419:30)
    at throwPluginError (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup\dist\rollup.js:15699:12)
    at Object.error (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup\dist\rollup.js:15754:24)
    at Object.error (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup\dist\rollup.js:16146:38)
    at RollupContext.error (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
    at lodash_2 (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:37:10)
    at arrayEach (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:516:11)
    at forEach (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9344:14)
    at _.each (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
    at Object.transform (C:\Users\Borewit\code\github\local-music-pwa\node_modules\rollup-plugin-typescript2\src\index.ts:212:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! music-pwa@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the music-pwa@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Borewit\AppData\Roaming\npm-cache\_logs\2019-09-04T06_04_40_351Z-debug.log
```

**Comment by minht11** [comment]
It should build now 🙂
